name: CI pipeline

on: 
  push: 
    branches:
      - master
jobs:
  project-testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt || true  # Allow failure
          pip install pandas scikit-learn mlflow seaborn dagshub

          # Skip backports.zoneinfo if Python >= 3.9
          python -c "import sys; sys.exit(0) if sys.version_info >= (3, 9) else sys.exit(1)" && \
          pip uninstall -y backports.zoneinfo || true
          pip install dvc

      - name: Check Installed Packages
        run: pip list

      - name: Set DAGSHUB_TOKEN environment variable
        run: echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Verify Environment Variable
        run: echo $DAGSHUB_TOKEN

      - name: Run DVC pipeline
        env: 
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc repro